/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LexiconRouteImport } from './routes/lexicon'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as ColophonRouteImport } from './routes/colophon'
import { Route as AttuneRouteImport } from './routes/attune'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtifactSlugRouteImport } from './routes/artifact.$slug'

const LexiconRoute = LexiconRouteImport.update({
  id: '/lexicon',
  path: '/lexicon',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const ColophonRoute = ColophonRouteImport.update({
  id: '/colophon',
  path: '/colophon',
  getParentRoute: () => rootRouteImport,
} as any)
const AttuneRoute = AttuneRouteImport.update({
  id: '/attune',
  path: '/attune',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactSlugRoute = ArtifactSlugRouteImport.update({
  id: '/artifact/$slug',
  path: '/artifact/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attune': typeof AttuneRoute
  '/compare': typeof CompareRoute
  '/colophon': typeof ColophonRoute
  '/directory': typeof DirectoryRoute
  '/lexicon': typeof LexiconRoute
  '/artifact/$slug': typeof ArtifactSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attune': typeof AttuneRoute
  '/compare': typeof CompareRoute
  '/colophon': typeof ColophonRoute
  '/directory': typeof DirectoryRoute
  '/lexicon': typeof LexiconRoute
  '/artifact/$slug': typeof ArtifactSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attune': typeof AttuneRoute
  '/compare': typeof CompareRoute
  '/colophon': typeof ColophonRoute
  '/directory': typeof DirectoryRoute
  '/lexicon': typeof LexiconRoute
  '/artifact/$slug': typeof ArtifactSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attune'
    | '/compare'
    | '/colophon'
    | '/directory'
    | '/lexicon'
    | '/artifact/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attune'
    | '/compare'
    | '/colophon'
    | '/directory'
    | '/lexicon'
    | '/artifact/$slug'
  id:
    | '__root__'
    | '/'
    | '/attune'
    | '/compare'
    | '/colophon'
    | '/directory'
    | '/lexicon'
    | '/artifact/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttuneRoute: typeof AttuneRoute
  CompareRoute: typeof CompareRoute
  ColophonRoute: typeof ColophonRoute
  DirectoryRoute: typeof DirectoryRoute
  LexiconRoute: typeof LexiconRoute
  ArtifactSlugRoute: typeof ArtifactSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lexicon': {
      id: '/lexicon'
      path: '/lexicon'
      fullPath: '/lexicon'
      preLoaderRoute: typeof LexiconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colophon': {
      id: '/colophon'
      path: '/colophon'
      fullPath: '/colophon'
      preLoaderRoute: typeof ColophonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attune': {
      id: '/attune'
      path: '/attune'
      fullPath: '/attune'
      preLoaderRoute: typeof AttuneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifact/$slug': {
      id: '/artifact/$slug'
      path: '/artifact/$slug'
      fullPath: '/artifact/$slug'
      preLoaderRoute: typeof ArtifactSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttuneRoute: AttuneRoute,
  CompareRoute: CompareRoute,
  ColophonRoute: ColophonRoute,
  DirectoryRoute: DirectoryRoute,
  LexiconRoute: LexiconRoute,
  ArtifactSlugRoute: ArtifactSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
